# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Multilingual documentation support
# Note: For language switching UI, configure translations in the
# Read the Docs dashboard (Admin > Translations)
translations:
  - language: ja
    build:
      sphinx:
        configuration: docs/conf.py
